[package]
name = "peekmore"
version = "0.1.0"
authors = ["foresterre <garm@ilumeo.com>"]
edition = "2018"
repository = "https://github.com/foresterre/peekmore"
readme = "README.md"
exclude = [
    ".idea/*",
    ".vscode/*",
    "*.iml",
]
keywords = ["peek", "lookahead", "iterator", "peekable", "look-ahead"]
categories = ["no-std"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
